### ISSUE TITLE
How to retract a fact?

### ISSUE THREAD

**Issue by theronic** [kristianmandrup/datascript-tutorial#9]
The ability to retract facts is mentioned, but how do you actually do it in DataScript?
https://github.com/kristianmandrup/datascript-tutorial/blob/master/retract_data.md

**Comment by kristianmandrup** [comment]
I suggest you ask Tonsky, datascript author or look into his examples/tests.

**Comment by theronic** [comment]
OK... why does this repo exist? I spent enough time looking for the answer (use :db/retract instead of :db/add) that it seemed warranted from a prominent DataScript tutorial. Should I open an issue in the future? :/

**Comment by kristianmandrup** [comment]
Please help add more/better docs! I personally don't use ClojureScript anymore... One reason is the lack of good docs!

**Comment by theronic** [comment]
OK, so a PR rather than an issue?
What do you use now, @kristianmandrup?

**Comment by kristianmandrup** [comment]
I've been searching for the holy Grail of web dev for the past 10 years. For now I have a service/component approach for both front and backend. On front-end via web components or custom elements, so you can mix and match whatever you like. Currently I think Vue2 and Cycle.js are the best. Tried out Elm but not my thing. Too constraining... Clojure had poor docs and too difficult to get going. Too high learning curve and investment needed for my taste.
Yeah, please do PRs or transfer it to Gitbook like I tried before.
